name: Flutter Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Flutter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable
          channel: stable

      - name: Debug Environment
        run: |
          flutter --version || echo "Flutter not installed"
          echo "GITHUB_ACTION_PATH: $GITHUB_ACTION_PATH"
          ls -la "$GITHUB_ACTION_PATH"

      - name: Force Flutter Installation
        run: |
          flutter precache
          flutter doctor -v

      - name: Get Flutter Dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web

      - name: Upload Web Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: build/web

      - name: Build APK
        run: flutter build apk

      - name: Upload APK Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: android-build
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Enable Desktop Platforms
        run: |
          flutter config --enable-linux-desktop
          flutter config --enable-windows-desktop
          flutter config --enable-macos-desktop

      - name: Build Linux Desktop
        run: flutter build linux

      - name: Upload Linux Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: build/linux

      - name: Build Windows Desktop
        run: flutter build windows

      - name: Upload Windows Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: build/windows