name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Vérifier le code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurer Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      # Récupérer les dépendances
      - name: Get dependencies
        run: flutter pub get

      # Exécuter les tests unitaires
      - name: Run tests
        run: flutter test

      # Construire l'application pour s'assurer qu'elle compile
      - name: Build APK
        run: flutter build apk --debug
